### ISSUE TITLE
Add hreflang tag for US English

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/approachable-io#1]
Google uses hreflang tags to match the user's language preference to the right variation of your pages. At this point in time, since we are currently supporting US English, we should add this to our `head` tag (between the `<head>` and `</head>` tags).

<link rel="alternate" href="http://www.approachble.io" hreflang="en-us" />

**Comment by MobGG** [comment]
PR: https://github.com/approachable-io/approachable-io/pull/17
