### ISSUE TITLE
Submit a site map

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/approachable-io#2]
We could use a sitemap to better help google crawl our website. This can be done by creating a new file called `sitemap.xml`. Currently, we only have one page, so the sitemap should look like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>http://www.example.net/?id=who</loc>
    <lastmod>2017-10-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
</urlset>
```

You can learn more about sitemaps here: https://en.wikipedia.org/wiki/Site_map

**Comment by solodynamo** [comment]
Working on this .

**Comment by solodynamo** [comment]
PR:https://github.com/approachable-io/approachable-io/pull/14
