### ISSUE TITLE
A better UX won't harm

### ISSUE THREAD

**Issue by akanshgulati** [approachable-io/approachable-io#28]
Currently, I see only textual content. Adding some colors and graphics is a good idea.

**Comment by LukeSchlangen** [comment]
I agree. Do you have any specifics? I don't want to add colors and graphics for the sake of adding colors and graphics, but if you have specific ideas, I'd be interested in hearing them!

**Comment by LukeSchlangen** [comment]
I'm going to close this. If we have specific UI things we want to tackle moving forward, let's add those individually.
