### ISSUE TITLE
404 "Approachable" link isn't actually approachable either.

### ISSUE THREAD

**Issue by izulien** [approachable-io/approachable-io#37]
### ISSUE TYPE
* [ ] Typo      
* [x] Bug       
* [ ] Feature   

### WHERE / WHAT

If you visit any site that would typically take you to a 404 page you will find the link below.

> [Approach some other page](http://www.approachable.io/approachable.io)

### EXPECTED BEHAVIOR

The 404 page should lead you back to the home page or another page that actually works.

### REPRODUCTION STEPS

1. Visit a non-real URL as a part of www.approachable.io domain
2. Follow the link shown.
3. Notice your URL changes to "http://www.approachable.io/approachable.io"
![image](https://user-images.githubusercontent.com/14319924/32032281-498aa1d6-b9d4-11e7-987a-d53c1125f2e1.png)

**Comment by LukeSchlangen** [comment]
Thanks @izulien for catching that! Thanks @Thunderbottom for the quick fix! #38
