### ISSUE TITLE
Create container and max width for body

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/approachable-io#8]
Limit the body width so that on wide screens, we don't lose readability.

```css
body {
  max-width: 900px;
}
```

This should also go hand in hand with centering the image, but that can be moved to a separate issue if you don't feel comfortable making that change.

**Comment by solodynamo** [comment]
I am working on this .

**Comment by solodynamo** [comment]
@LukeSchlangen We should not define a `max-width` on body as whole website would get limited width on large screen instead we should define that body always takes 100% both in width and height of the screen and not less or more.

**Comment by LukeSchlangen** [comment]
That's a good point, but on a mobile screen, I would expect the height to be more than `100%`? Maybe what I'm really looking for is padding around the text?

**Comment by solodynamo** [comment]
PR: https://github.com/approachable-io/approachable-io/pull/13
